baseURL: "/"
languageCode: en
DefaultContentLanguage: en
title: Samrit Pramanik
theme: anatole
summarylength: 20
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
taxonomies:
  category: categories
  series: series
  tag: tags
